fix: an attempt to address the tracer leak issue
Following the error trackback

----

jax.errors.UnexpectedTracerError: Encountered an unexpected tracer. A function transformed by JAX had a side effect, allowing for a reference to an intermediate value with type float32[4002] wrapped in a DynamicJaxprTracer to escape the scope of the transformation.
JAX transformations require that functions explicitly return their outputs, and disallow saving intermediate values to global state.
The function being traced when the value leaked was sample at /home/meesum/academia/gwkokab/.venv/lib/python3.13/site-packages/equinox/_jit.py:43 traced for jit.
------------------------------
The leaked intermediate value was created on line /home/meesum/academia/gwkokab/.venv/lib/python3.13/site-packages/gwkokab/cosmology/_cosmology.py:62:18 (Cosmology.__init__).
------------------------------
When the value was created, the final 5 stack frames (most recent last) excluding JAX-internal frames were:
------------------------------
/home/meesum/academia/gwkokab/.venv/lib/python3.13/site-packages/gwkokab/cosmology/_planck.py:58:11 (default_cosmology)
/home/meesum/academia/gwkokab/.venv/lib/python3.13/site-packages/gwkokab/cosmology/_planck.py:18:11 (PLANCK_2013_Cosmology)
/home/meesum/academia/gwkokab/.venv/lib/python3.13/site-packages/equinox/_module/_module.py:396:29 (_ModuleMeta.__call__)
/home/meesum/academia/gwkokab/.venv/lib/python3.13/site-packages/equinox/_module/_better_abstract.py:233:15 (BetterABCMeta.__call__)
/home/meesum/academia/gwkokab/.venv/lib/python3.13/site-packages/gwkokab/cosmology/_cosmology.py:62:18 (Cosmology.__init__)
------------------------------

To catch the leak earlier, try setting the environment variable JAX_CHECK_TRACER_LEAKS or using the `jax.checking_leaks` context manager.
See https://docs.jax.dev/en/latest/errors.html#jax.errors.UnexpectedTracerError