sage scripts in `kokab` namespace (#233)
* chore: intitial utils for sage scripts

* chore: sage script for n-powerlaw-m-gaussains

* chore: flowMC arguments shifted to json file

* chore: multiple rates prior

* Squashed commit of the following:

commit bbc78619d57765800175dcfa2abca9a05bd92804
Author: Meesum Qazalbash <meesumqazalbash@gmail.com>
Date:   Sat Sep 14 01:06:42 2024 +0500

    refactor: emoji free issue/pr labels and accordingly updated scripts (#236)

    refactor: emoji free issue/pr labels and accordingly updated scripts

commit 5005c1188b6faaf17a2cca2c6c6d14b130e8604c
Author: Qazalbash <meesumqazalbash@gmail.com>
Date:   Sat Sep 14 00:49:06 2024 +0500

    Revert "chore: support python3.9"

    This reverts commit 5e4ecc371c2a727367879f62f577464397388795.

commit 5e4ecc371c2a727367879f62f577464397388795
Author: Qazalbash <meesumqazalbash@gmail.com>
Date:   Sat Sep 14 00:45:14 2024 +0500

    chore: support python3.9

commit aff0c6dbb888633c17446582fda5f25287bc60d6
Author: Meesum Qazalbash <meesumqazalbash@gmail.com>
Date:   Thu Sep 12 16:33:00 2024 +0500

    chore: friendship ended with polars now pandas is my friend (#235)

* chore: no polars only pandas

* refactor: Update sage.py and common.py

Refactor the code in sage.py and common.py to improve readability and maintainability.

- In sage.py:
  - Import the `enable_debugging` function from `gwkokab.debug`
  - Import the `flowMC_json_read_and_process` function from `..utils.common`
  - Remove the unused `prior_group` and `--prior-json` argument
  - Add a check for the `--verbose` flag and enable debugging if it is set
  - Update the `FLOWMC_HANDLER_KWARGS` dictionary with the processed `flowMC_json` data
  - Update the initialization of `KEY1`, `KEY2`, and `KEY3` using `jrd.split`
  - Update the initialization of `N_CHAINS` using `FLOWMC_HANDLER_KWARGS["sampler_kwargs"]["n_chains"]`
  - Update the initialization of `initial_position` using `poisson_likelihood.priors.sample`
  - Update the initialization of `FLOWMC_HANDLER_KWARGS["nf_model_kwargs"]["n_features"]` and `FLOWMC_HANDLER_KWARGS["sampler_kwargs"]["n_dim"]` with the shape of `initial_position`
  - Update the `FLOWMC_HANDLER_KWARGS["data_dump_kwargs"]["labels"]` with the expanded arguments and model variables

- In common.py:
  - Add the `flowMC_json_read_and_process` function to read and process a JSON file
  - Update the `expand_arguments` function to handle exact matches
  - Update the `match_all` function to handle exact matches

These changes improve the code structure and make it easier to understand and maintain.

* Squashed commit of the following:

commit 9083f2b3f82acefa4414ff8f7c20a7082f96cbfb
Author: Meesum Qazalbash <meesumqazalbash@gmail.com>
Date:   Sat Sep 14 23:30:38 2024 +0500

    refactor: update script paths in pyproject.toml (#238)

commit bbc78619d57765800175dcfa2abca9a05bd92804
Author: Meesum Qazalbash <meesumqazalbash@gmail.com>
Date:   Sat Sep 14 01:06:42 2024 +0500

    refactor: emoji free issue/pr labels and accordingly updated scripts (#236)

    refactor: emoji free issue/pr labels and accordingly updated scripts

commit 5005c1188b6faaf17a2cca2c6c6d14b130e8604c
Author: Qazalbash <meesumqazalbash@gmail.com>
Date:   Sat Sep 14 00:49:06 2024 +0500

    Revert "chore: support python3.9"

    This reverts commit 5e4ecc371c2a727367879f62f577464397388795.

commit 5e4ecc371c2a727367879f62f577464397388795
Author: Qazalbash <meesumqazalbash@gmail.com>
Date:   Sat Sep 14 00:45:14 2024 +0500

    chore: support python3.9

commit aff0c6dbb888633c17446582fda5f25287bc60d6
Author: Meesum Qazalbash <meesumqazalbash@gmail.com>
Date:   Thu Sep 12 16:33:00 2024 +0500

    chore: friendship ended with polars now pandas is my friend (#235)

* fix: plotting scripts path fixed

* refactor: Update sage.py and common.py

- Refactor sage.py and common.py to improve code organization and readability.
- Removed unused imports and variables.
- Updated function names and variable names for clarity.
- Extracted common functions to a separate module for reusability.
- Added type hints for better code documentation.

* refactor: kokab.utils.commons for better readibility

* chore: better error handling while loading posterior data

* Squashed commit of the following:

commit 0e6a4be211c95b02023891f2b6c6b9282999e461
Author: Meesum Qazalbash <meesumqazalbash@gmail.com>
Date:   Sun Sep 15 18:13:48 2024 +0500

    CodeCov in GWKokab (#239)

    * CodeCov in GWKokab

    * chore: codecov badge in README

    * chore: codecov configuration

    * Update .codecov.yml

    - update codecov comment layout

* chore: refactor n_pl_m_g with no-spin and no-tilt flags

* chore: parameter for inference fixed by choice of model in n_pl_m_g

* chore: no spin no tilt case in n_pl_m_g

* fix: plotting scripts path and header reading bug (#242)

* chore: validate tranformations

* fix: PrimaryMassAndMassRatioToComponentMassesTransform domain and codomain fixed

* fix: unique interval dimension

* chore: sage script for eccentricity matters

* chore: eccentricity matters, eccentricity models fixed to half normal

* chore: multirate disabled from eccentricity model

* fix: dict passed as prior

```bash
/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/kokab/ecc_matters/sage.py:57: Warning: If you have made any changes to any parameters, please make sure that the changes are reflected in scripts that generate plots.
  warnings.warn(
Traceback (most recent call last):
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/bin/sage_ecc_matters", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/kokab/ecc_matters/sage.py", line 108, in main
    poisson_likelihood.set_model(
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/gwkokab/_src/inference/poissonlikelihood.py", line 195, in set_model
    self.priors = JointDistribution(*log_rates_prior, *self.variables.values())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/numpyro/distributions/distribution.py", line 100, in __call__
    return super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/gwkokab/_src/models/utils.py", line 52, in __init__
    *tuple(d.batch_shape for d in self.marginal_distributions)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/gwkokab/_src/models/utils.py", line 52, in <genexpr>
    *tuple(d.batch_shape for d in self.marginal_distributions)
           ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'batch_shape'
```