gh-322: Implementation of `ScaledMixture` and relevant refactoring (#323)
* chore: implementation of ScaledMixture

* chore: NPowerLawMGaussian converted to ScaledMixture

* refactor: poisson likelihood for ScaledMixture

* refactor: Remove unused is_multi_rate_model flag in PoissonLikelihood class

* refactor: Remove unused attributes from sage

* fix: log rate regex parsing

2024-10-12 15:09:02.055369: I external/xla/xla/pjrt/pjrt_c_api_client.cc:126] PjRtCApiClient created.
/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/kokab/n_pls_m_gs/sage.py:86: Warning: If you have made any changes to any parameters, please make sure that the changes are reflected in scripts that generate plots.
  warnings.warn(
Traceback (most recent call last):
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/bin/sage_n_pls_m_gs", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/kokab/n_pls_m_gs/sage.py", line 171, in main
    model_prior_param = get_processed_priors(extended_params, prior_dict)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/kokab/utils/common.py", line 100, in get_processed_priors
    matched_prior_params = match_all(params, priors)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/kokab/utils/regex.py", line 54, in match_all
    if matches_regex(pattern, string):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/site-packages/kokab/utils/regex.py", line 29, in matches_regex
    return bool(re.fullmatch(pattern, string))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/muhammad.zeeshan/.conda/envs/kvenv/lib/python3.11/re/__init__.py", line 171, in fullmatch
    return _compile(pattern, flags).fullmatch(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'tuple'

* fix: rate parameters added two times in headers

* Refactor models tests (#325)

Refactor distributions tests with removal of scipy distributions and key word argument based test cases

* Tests for NPowerLawMGaussians (#326)

Refactor distributions tests with removal of scipy distributions and key word argument based test cases

* tests for NPowerLawMGaussian

* fix: log_rate exponentiated in the expected rate integral

* Refactor log_rates calculation in NPowerLawMGaussian and ppd calculation